### ISSUE TITLE
Feeds with lots of pictures hangs the Tidings

### ISSUE THREAD

**Issue by veteli** [pycage/tidings#25]
When rss feed has lots of pictures Tidings hangs and sometime even crashes. Also whole Jolla phone feels really slow when Tidings is loading these feeds.
To reproduce:
- Open newist post for example from: http://www.haukkari.net/feeds/posts/
- Slowly start scrolling down the last post (or some of the previous)
- Feed is scrolled little bit, but then comes the "Tidings not responding" -notification.
- If you wait for all the pictures to be loaded then you can proceed, but if you try to proceed scrolling the Tidings crashes.

**Comment by pycage** [comment]
Thanks for the link. I'll try to see what can be done about that.

**Comment by pycage** [comment]
The DCIM images in full resolution on the blog are too much for the limited RAM of the device.
Tidings 0.6.0 will have an option to block automated loading of images. The images can be viewed one by one on the new Resources page.

**Comment by pycage** [comment]
This should be fixed already since 0.6.0 and this issue can be closed.
