### ISSUE TITLE
Selecting first feed shows articles from all feeds

### ISSUE THREAD

**Issue by accumulator** [pycage/tidings#26]
I have 3 feeds in Tidings. When selecting either of the last two, I see only articles from the selected feed. When I select the first one (Engadget, the pre-installed one) I see articles from all feeds.

**Comment by pycage** [comment]
What is your sorting settings in the feed list set to?

**Comment by accumulator** [comment]
sorry, I only days ago found this is managed through sorting setting from pulley :)
