### ISSUE TITLE
Time is wrong with Atom feeds having RFC2822Date

### ISSUE THREAD

**Issue by tace** [pycage/tidings#28]
E.g. together.jolla.com feed having dates like this.
Mon, 05 Jan 2015 18:40:51 +0200

Times are off by timezone amount (too much), this causes latest (newer than 2 hours in this case) topics are not shown on list or shown as future time.

I noticed this as I was using your dateparser.h module in jolla2gether app as well and got same problems there. 
So dataParser.parse returns time as converted to localtime i.e. timezone 2 hours is added to timevalue. So when converting that to seconds and comparing to current time it does not work as current time is in UTC. 

So for now I fixed this in jolla2gether like this: 

        var date = dateParser.parse(rssPubDate)

        // dateParser returns date as converted to local time (e.g. to be shown in GUI),
        // but timezone information is still available.
        // To make returned seconds comparable to current time (seconds), we need to
        // change time to UTC as it's compared to current time (returned by JavaScript Date.now())
        // which is also in UTC.
        var currentDate = date;
        var currentTime = currentDate.getTime(); // this ignores timezone
        var localOffset =  date.getTimezoneOffset() * 60000; // timezone seconds
        return Math.round(new Date(currentTime + localOffset).getTime() / 1000);

**Comment by pycage** [comment]
Thanks for nailing this down! I already suspected something like this.

**Comment by pycage** [comment]
I think I was able to fix the issue in dateparser.h by manually extracting and applying the GMT offset.
This issue should thus be fixed with Tiding 0.6.0.

**Comment by pycage** [comment]
This is fixed. Closing bug.
