### ISSUE TITLE
Tidings cannot update RSS from Hackernews/hnapp.com

### ISSUE THREAD

**Issue by jyry** [pycage/tidings#30]
I'm using hnapp.com to fetch Hackernews RSS feed in Tidings. The RSS feed does not update and Tidings shows a spinning graphic like it is updating but nothing happens. I have removed Tidings settings and still no help. 

The URL I'm using is: http://hnapp.com/rss?q=score>70

**Comment by pycage** [comment]
Thanks for reporting this bug.
It will be fixed in the next version.

**Comment by pycage** [comment]
This is fixed. Closing bug.
