### ISSUE TITLE
Add feed button not visible on Fairphone 2

### ISSUE THREAD

**Issue by m01** [pycage/tidings#40]
When using this app on Sailfish OS on the Fairphone 2, the + button for adding feeds is not visible:

![20160516174114](https://cloud.githubusercontent.com/assets/783973/15301248/b55f7d48-1ba4-11e6-8752-1c322650c6dd.jpg)

**Comment by pycage** [comment]
The (+) button is only visible in edit mode (tap and hold on a feed). Could this be the reason why it's not there?

**Comment by m01** [comment]
Doh! I did not realise I had to enter edit mode. I was looking for an "add feed" option in the pulley menu.
I also think I may have accidentally dismissed the tutorial tip too quickly...
Thank you!
