### ISSUE TITLE
"Full article" and "Website" button missing from some feeds

### ISSUE THREAD

**Issue by dyraig** [pycage/tidings#41]
I use Tidings on a daily basis and overall, I'm very happy with it. However, there a some feeds, where the article do not have the "Full article" and "Website" buttons underneath them - so if I want to read more on a particular article, I have to open up the webbrowser, go to that site and search for the article in question - which kind defeats the purpose.

Two feeds where that happens are: 
- http://www.ligfiets.net/advertisement/rss.xml
- http://www.ligfiets.net/news/rss.xml
  (both from the same site)

If you could get Tiding to deal with those as well, that would be really great.

**Comment by pycage** [comment]
Thanks for reporting. This is now fixed in latest master.
