### ISSUE TITLE
Reusing the RescalingRichText item

### ISSUE THREAD

**Issue by Max-Might** [pycage/tidings#43]
Hello.

I have used the RescalingRichText qml item in an open source project of mine and I was wondering if that is OK and if yes what is the proper way to credit you as the author of this class.
Currently it can be found here: https://gitlab.com/maxmight/GuildWarsDaily/blob/master/qml/components/RescalingRichText.qml

I have added a note to point the origin of the source for the file.

**Comment by pycage** [comment]
Hi,

thanks for notifying me. I'm happy that you found the RescalingRichText element useful!
It's fine if you mention me (Martin Grimme) as the author and Tidings as the project from where it's from.

**Comment by pycage** [comment]
I guess this issue can be closed as everyone is happy. :)
