### ISSUE TITLE
Resolution too low in XperiaX

### ISSUE THREAD

**Issue by TMavica** [pycage/tidings#47]
Aa title

**Comment by TMavica** [comment]
no news?

**Comment by pycage** [comment]
Not yet. Sorry. :(

**Comment by Ygarr** [comment]
Also on Jolla 1 time string partially overlap news header.

**Comment by pycage** [comment]
The Xperia X scaling issues should be fixed in latest master.
As for the Jolla 1 time string, I'm not able to reproduce this overlapping.
