### ISSUE TITLE
Loaded images are blue

### ISSUE THREAD

**Issue by raketti** [pycage/tidings#58]
When loading images for an article, all the images get this strange blue tint in the feed/article view compared to the original ones.

**Comment by pycage** [comment]
I'm afraid that this is a problem with Qt Webkit on Sailfish. It seems like the endianess of byte ordering is wrong on this system. This should be fixed by Jolla in Qt.

**Comment by raketti** [comment]
Ok, seems that too many issues rise with the "solution" that "Jolla needs to fix this." Anyway, thanks for a great app! :)
